/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class team_fileoperations_FileOperationsImp */

#ifndef _Included_team_fileoperations_FileOperationsImp
#define _Included_team_fileoperations_FileOperationsImp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     team_fileoperations_FileOperationsImp
 * Method:    findURootDirCImp
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_team_fileoperations_FileOperationsImp_findURootDirCImp
  (JNIEnv *, jobject);

/*
 * Class:     team_fileoperations_FileOperationsImp
 * Method:    findBackupDirCImp
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_team_fileoperations_FileOperationsImp_findBackupDirCImp
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
